### ISSUE TITLE
Updating event with new descrption does not save/update

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1116]

**Comment by gnunicorn** [comment]
this time we should add integration tests for it!

**Comment by kumarpalsinh25** [comment]
@bitfriend 
Not sure, I think issue is on either of below code.


[acter_flutter_sdk_ffi.dart](https://github.com/acterglobal/a3/blob/main/app/packages/rust_sdk/lib/acter_flutter_sdk_ffi.dart)

 ```
 /// update builder
  CalendarEventUpdateBuilder updateBuilder() {
    var tmp0 = 0;
    tmp0 = _box.borrow();
    final tmp1 = _api._calendarEventUpdateBuilder(
      tmp0,
    );
```


  ```
/// set description text
  void descriptionText(
    String body,
  ) {
```

**Comment by emilvincentz** [comment]
this is also the same for pins.

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Is this issue is fixed by https://github.com/acterglobal/a3/pull/1479?

**Comment by gnunicorn** [comment]
should have been. but if @emilvincentz still reports it, it might not be?!?

**Comment by emilvincentz** [comment]
just tested on the latest nightly, but problem still persist

**Comment by bitfriend** [comment]
Yes, correct.
I had implemented test of calendar event updating, but it failed.
Will dig into the detailed logs.

**Comment by emilvincentz** [comment]
As far as I remember, also happens on description in pins

**Comment by bitfriend** [comment]
Probably.
I am confident editing of custom event (pin, news, calendar event, etc) has the issue.
I found something.

**Comment by emilvincentz** [comment]
Has this issue been fixed/merged already? or not yet?
