### ISSUE TITLE
Fatal error: operation not permitted (os error 1)

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1422]
happens both on Iphone and MacOS. 
Note sure what causes it. But it seems to come when im opening the app after some time or close the app to reopen, but not always.

![Image](https://github.com/acterglobal/a3/assets/77483554/c8dd60ba-cd8c-4c97-9fcc-c6d1f2e31392)

**Comment by gnunicorn** [comment]
@emilvincentz a fix has been merged. Can you try latest release?

**Comment by emilvincentz** [comment]
unfortunately still persists with latest iOS version from App Store (also send via bug report)

**Comment by gnunicorn** [comment]
@emilvincentz but this doesn't happen every time? Just some times? what a weird bug...

**Comment by emilvincentz** [comment]
it seems to happen often I click on a push notification and it goes to the app

**Comment by emilvincentz** [comment]
other user @helena:acter.global just reported this bug as well.

![Image](https://github.com/acterglobal/a3/assets/77483554/abf1bb9d-c344-4479-b63e-7076d3b3e334)

**Comment by gnunicorn** [comment]
@emilvincentz that is also iOS I assume?

**Comment by emilvincentz** [comment]
Will confirm

**Comment by emilvincentz** [comment]
Its Iphone

**Comment by gnunicorn** [comment]
was this being on LTE only? So no WiFi? [Seems to be the conditions when other apps have this being reported](https://github.com/rustdesk/rustdesk/issues/959)...

**Comment by emilvincentz** [comment]
hmm dont think so, as it has also happened at the office where its connected to the wifi. 
will double check (when I can test Acter again, currently not possible due to white screen issue).

**Comment by emilvincentz** [comment]
Actually I dont think LTE only can be the thing, as this also happens on MacOS who only is connected to wifi

**Comment by gnunicorn** [comment]
temporarily fixed by #1489

**Comment by emilvincentz** [comment]
The OS Error 1, just happened again this morning. 
Also the Yiahaa button is still not responsive.

**Comment by emilvincentz** [comment]
Also still experiencing this on IOS.
At the same time while trying to write in element to share the bug, Element also crashed.

https://github.com/acterglobal/a3/assets/77483554/5bb128d9-1749-4de6-a050-d48cb2ddd8d8

![Image](https://github.com/acterglobal/a3/assets/77483554/783120cc-f4a3-4cbb-a3a3-1bcac4b0f206)

![Image](https://github.com/acterglobal/a3/assets/77483554/2ceca30c-acf5-4c60-a2f4-06ae93901b4a)

**Comment by emilvincentz** [comment]
both IOS and MacOs shows this error when i opened both for the first time this morning.
unfortunately still cant bug repport

**Comment by emilvincentz** [comment]
Do we know why this is happening?

**Comment by gnunicorn** [comment]
> Do we know why this is happening?

no, not a clue. The error we had seen on one of the dev's system was solved with a hotfix/revert last week. We don't have any device at hand that can give us more information.

@emilvincentz can you run the macos version from the terminal? Just go the directory of acter and type `open Acter.app` and paste the output the terminal gives. Maybe that can help us somehow...?!?

**Comment by emilvincentz** [comment]
@gnunicorn I have already nuked the data and opened the app. will try to do this next time though.
is there something similiar I can do on IOS? havent nuked the data there yet

**Comment by emilvincentz** [comment]
not sure, but might have found something that relates to the os error 1 issue. 

I saw a bug on MacOS. I entered a chat and it showed and error. something like "error loading members" or somehting. (i have just reported the bug and with screenshot).
I then decided to close the app and reopen. And this time it showed the os error 1. 
Thought there might be a link between those two, but not sure.

**Comment by emilvincentz** [comment]
also found this, when going to the terminal and opening Acter:

Last login: Thu Mar 14 10:42:01 on ttys000
/Applications/Acter.app/Contents/MacOS/Acter ; exit;                            
emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter ; exit;
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
flutter: handle error - address: 105553167584448 ; len: 36
2024-03-14 10:44:36.020 Acter[57846:3579077] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

**Comment by emilvincentz** [comment]
then this is how the logs show, when i nuke the local data:

Last login: Thu Mar 14 10:44:29 on ttys001
/Applications/Acter.app/Contents/MacOS/Acter ; exit;                            
emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter ; exit;
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
flutter: handle error - address: 105553180460544 ; len: 36
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Deletion failed, path = '/Users/emil/Library/Containers/global.acter.a3/Data/Library/Application Support/global.acter.a3' (OS Error: No such file or directory, errno = 2)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 57955, tid: 6173388800, name io.flutter.ui
os: macos arch: arm64 comp: no sim: no
build_id: '9533f02aa10737df98cd46bbc6825fc0'
isolate_dso_base: 112994000, vm_dso_base: 112994000
isolate_instructions: 11299f040, vm_instructions: 112994d00
    #00 abs 00000001129b6f4f _kDartIsolateSnapshotInstructions+0x17f0f
    #01 abs 0000000113072e3f _kDartIsolateSnapshotInstructions+0x6d3dff
    #02 abs 000000011315d093 _kDartIsolateSnapshotInstructions+0x7be053
    #03 abs 00000001129a6057 _kDartIsolateSnapshotInstructions+0x7017
    #04 abs 00000001129a5c7b _kDartIsolateSnapshotInstructions+0x6c3b
    #05 abs 00000001129a5bef _kDartIsolateSnapshotInstructions+0x6baf
    #06 abs 00000001129a5927 _kDartIsolateSnapshotInstructions+0x68e7
    #07 abs 000000011315c42b _kDartIsolateSnapshotInstructions+0x7bd3eb
    #08 abs 00000001129a589f _kDartIsolateSnapshotInstructions+0x685f


Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by emilvincentz** [comment]
and this the logs that shows when i open the app (succesfully after nuking the data)

Last login: Thu Mar 14 10:49:21 on ttys000
/Applications/Acter.app/Contents/MacOS/Acter ; exit;                            
emil@Matildes-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter ; exit;
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
2024-03-14 10:53:04.557 Acter[58151:3588322] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

**Comment by emilvincentz** [comment]
e

**Comment by emilvincentz** [comment]
And this is how the logs look like when i first logged in again:
One of the errors that seem to occcur i the logs, (maybe this is normal) but thought i just want to highlight, is 
"[2024-03-14][11:06:31.787506][matrix_sdk_crypto::machine][WARN] Failed to decrypt a room event: Can't find the room key to decrypt the event, withheld code: None

### Full logs:


[Terminal Saved Output.txt](https://github.com/acterglobal/a3/files/14600733/Terminal.Saved.Output.txt)

**Comment by emilvincentz** [comment]
Cool.
let me know if I need/can do anything else.

**Comment by gnunicorn** [comment]
@emilvincentz you dont happen to remember if that last sentence in the error I quoted above only appeared after you started the nuking process? Because I can't really find any other explanation for it :(

**Comment by emilvincentz** [comment]
yes, it only appeared after I nuked the data

**Comment by emilvincentz** [comment]
Sharing logs from this morning, where the error showed again. 
Its weird, its like it somehow seems to happen everytime in the morning (like after i havent used Acter for a while and it has been shut down for a while). Not sure if this helps though:

Last login: Fri Mar 15 09:24:31 on ttys000
/Applications/Acter.app/Contents/MacOS/Acter ; exit;
emil@Matildes-MacBook-Air ~ % /Applications/Acter.app/Contents/MacOS/Acter ; exit;
flutter: log settings: acter::api::client=trace,acter::api::spaces=trace,acter_core::executor=trace,acter_core=debug,acter=warn,a3=warn,warn
flutter: logs will be found in /Users/emil/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3
flutter: handle error - address: 105553172974544 ; len: 36
2024-03-15 09:24:54.191 Acter[65720:3966995] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

**Comment by gnunicorn** [comment]
@emilvincentz can you stop it, then [try to give it "full disk access" as described here](https://www.technewstoday.com/fix-operation-not-permitted-on-mac/) and try again?

**Comment by emilvincentz** [comment]
@gnunicorn could it be linked to some type of loading issue? 
I cant say why, but i just new when i saw this loading error, that if i closed the app and reopned, it would show the os erro 1:


https://github.com/acterglobal/a3/assets/77483554/7390e9d9-40cb-4b52-bc57-018c84eed121

**Comment by kumarpalsinh25** [comment]
@gnunicor
Today I faced the same error on the debug mode of the mac desktop app. Here fetch the logs from console.

```
flutter: INFO: 2024-03-22 10:41:55.747500: 0 sessions stored
flutter: INFO: 2024-03-22 10:41:55.747900: getting location for name: "main"
flutter: INFO: 2024-03-22 10:41:55.748211: going to /
flutter: INFO: 2024-03-22 10:41:55.748611: getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
flutter: INFO: 2024-03-22 10:41:55.749128: redirecting to RouteMatchList#322dd(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#aad24(route: GoRoute#b3e92(parentNavKey: [LabeledGlobalKey<NavigatorState>#f6bb8 root], name: "fatalFail", path: "/error"))])
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Deletion failed, path = '/Users/kumarpalsinh/Library/Containers/global.acter.a3/Data/Library/Application Support/global.acter.a3/DEV' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185:7)
#2      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
#3      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
#4      Future._completeWithValue (dart:async/future_impl.dart:647:5)
#5      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

[a3::sdk] 0 sessions stored
[GoRouter] getting location for name: "main"
[GoRouter] going to /
[GoRouter] getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
[GoRouter] redirecting to RouteMatchList#322dd(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#aad24(route: GoRoute#b3e92(parentNavKey: [LabeledGlobalKey<NavigatorState>#f6bb8 root], name: "fatalFail", path: "/error"))])
```

**Comment by emilvincentz** [comment]
Okey, i just tested if the bug also happens when im logged out of Acter.
This i can confirm on MacOS.

**Comment by emilvincentz** [comment]
Also tested that the bug happens even when im logged out. 
So it shouldnt have anything to do with account.

**Comment by emilvincentz** [comment]
So on IOS i hasnt experienced this for some days now. However the bugs i see instead is #1541 Maybe they are linked somehow?

**Comment by emilvincentz** [comment]
Operation not permitted (os error 1)

**Comment by kumarpalsinh25** [comment]
```
flutter: INFO: 2024-03-25 16:32:04.373769: 0 sessions stored
flutter: INFO: 2024-03-25 16:32:04.374554: getting location for name: "main"
flutter: INFO: 2024-03-25 16:32:04.374955: going to /
flutter: Fatal error: Operation not permitted (os error 1)
flutter: Stack: 
flutter: INFO: 2024-03-25 16:32:04.375676: getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
flutter: INFO: 2024-03-25 16:32:04.376590: redirecting to RouteMatchList#8af78(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#3b760(route: GoRoute#b8b35(parentNavKey: [LabeledGlobalKey<NavigatorState>#1290e root], name: "fatalFail", path: "/error"))])
[a3::sdk] 0 sessions stored
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Deletion failed, path = '/Users/kumarpalsinh/Library/Containers/global.acter.a3/Data/Library/Application Support/global.acter.a3/DEV' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185:7)
#2      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
#3      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
#4      Future._completeWithValue (dart:async/future_impl.dart:647:5)
#5      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

[GoRouter] getting location for name: "main"
[GoRouter] going to /
[GoRouter] getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
[GoRouter] redirecting to RouteMatchList#8af78(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#3b760(route: GoRoute#b8b35(parentNavKey: [LabeledGlobalKey<NavigatorState>#1290e root], name: "fatalFail", path: "/error"))])

```

**Comment by emilvincentz** [comment]
hey @kumarpalsinh25 what time did you experience the crash today? 
It happened to me around 1 hour ago. I wonder if it happened around the same time?

**Comment by kumarpalsinh25** [comment]
> hey @kumarpalsinh25 what time did you experience the crash today? It happened to me around 1 hour ago. I wonder if it happened around the same time?

Just now when I run the desktop app from the `main` branch using android studio.

**Comment by gnunicorn** [comment]
@emilvincentz, @kumarpalsinh25  I've just submitted #1551 in an attempt to give us more input about where this exactly happens. After the merge, if that happens again, please post your logs here, so I can investigate further!

**Comment by kumarpalsinh25** [comment]
@gtalha07 
Have you ever faced this issue on your mac or iphone?

**Comment by kumarpalsinh25** [comment]
@gnunicorn 
Latest build full logs.

```
Debug service listening on ws://127.0.0.1:57060/7sopQcI5RWQ=/ws
Syncing files to device macOS...
flutter: INFO: 2024-03-29 12:32:41.098082: Full paths for routes:
flutter:   => /forward
flutter:   => /intro
flutter:   => /start
flutter:   => /introProfile
flutter:   => /login
flutter:   => /forgotPassword
flutter:   => /register
flutter:   => /bug-report
flutter:   => /error
flutter:   => /quick-jump
flutter:   => /actions/addPin
flutter:   => /actions/addTaskList
flutter:   => /actions/createSuperInvite
flutter:   => /spaces/create
flutter:   => /:spaceId([!#][^/]+)/linkChat
flutter:   => /:spaceId([!#][^/]+)/linkSubspace
flutter:   => /:spaceId([!#][^/]+)/linkRecommended
flutter:   => /actions/addUpdate
flutter:   => /:spaceId([!#][^/]+)/edit
flutter:   => /:spaceId([!#][^/]+)/invite
flutter:   => /:roomId([!#][^/]+)/invite
flutter:   => /chat/create
flutter:   => /
flutter:   => /search
flutter:   => /dashboard
flutter:   => /settings
flutter:   => /info/licenses
flutter:   => /settings/labs
flutter:   => /settings/notifications
flutter:   => /settings/super_invites
flutter:   => /info
flutter:   => /profile
flutter:   => /settings/sessions
flutter:   => /settings/language
flutter:   => /settings/emailAddresses
flutter:   => /settings/blockedUsers
flutter:   => /:spaceId([!#][^/]+)/spaces
flutter:   => /:spaceId([!#][^/]+)/members
flutter:   => /:spaceId([!#][^/]+)/pins
flutter:   => /:spaceId([!#][^/]+)/events
flutter:   => /:spaceId([!#][^/]+)/chats
flutter:   => /:spaceId([!#][^/]+)/tasks
flutter:   => /:spaceId([!#][^/]+)
flutter:   => /spaces/join
flutter:   => /spaces
flutter:   => /:spaceId([!#][^/]+)/settings
flutter:   => /:spaceId([!#][^/]+)/settings/app
flutter:   => /:spaceId([!#][^/]+)/settings/notifications
flutter:   => /tasks
flutter:   => /tasks/:taskListId([^/]+)/:taskId([^/]+)
flutter:   => /tasks/:taskListId([^/]+)
flutter:   => /pins
flutter:   => /pins/:pinId
flutter:   => /events
flutter:   => /events/create
flutter:   => /events/:calendarId/edit
flutter:   => /events/:calendarId
flutter:   => /chat
flutter:   => /chat/:roomId([!#][^/]+)
flutter:   => /chat/:roomId([!#][^/]+)/profile
flutter:   => /activities
flutter: known full paths for route names:
flutter:   forward => /forward
flutter:   intro => /intro
flutter:   start => /start
flutter:   introProfile => /introProfile
flutter:   authLogin => /login
flutter:   forgotPassword => /forgotPassword
flutter:   authRegister => /register
flutter:   bugReport => /bug-report
flutter:   fatalFail => /error
flutter:   quickJump => /quick-jump
flutter:   actionAddPin => /actions/addPin
flutter:   actionAddTaskList => /actions/addTaskList
flutter:   actionCreateSuperInvite => /actions/createSuperInvite
flutter:   createSpace => /spaces/create
flutter:   linkChat => /:spaceId([!#][^/]+)/linkChat
flutter:   linkSubspace => /:spaceId([!#][^/]+)/linkSubspace
flutter:   linkRecommended => /:spaceId([!#][^/]+)/linkRecommended
flutter:   actionAddUpdate => /actions/addUpdate
flutter:   editSpace => /:spaceId([!#][^/]+)/edit
flutter:   spaceInvite => /:spaceId([!#][^/]+)/invite
flutter:   chatInvite => /:roomId([!#][^/]+)/invite
flutter:   createChat => /chat/create
flutter:   main => /
flutter:   search => /search
flutter:   dashboard => /dashboard
flutter:   settings => /settings
flutter:   licenses => /info/licenses
flutter:   settingsLabs => /settings/labs
flutter:   settingNotifications => /settings/notifications
flutter:   settingsSuperInvites => /settings/super_invites
flutter:   info => /info
flutter:   myProfile => /profile
flutter:   settingSessions => /settings/sessions
flutter:   settingLanguage => /settings/language
flutter:   emailAddresses => /settings/emailAddresses
flutter:   blockedUsers => /settings/blockedUsers
flutter:   spaceRelatedSpaces => /:spaceId([!#][^/]+)/spaces
flutter:   spaceMembers => /:spaceId([!#][^/]+)/members
flutter:   spacePins => /:spaceId([!#][^/]+)/pins
flutter:   spaceEvents => /:spaceId([!#][^/]+)/events
flutter:   spaceChats => /:spaceId([!#][^/]+)/chats
flutter:   spaceTasks => /:spaceId([!#][^/]+)/tasks
flutter:   space => /:spaceId([!#][^/]+)
flutter:   joinSpace => /spaces/join
flutter:   spaces => /spaces
flutter:   spaceSettings => /:spaceId([!#][^/]+)/settings
flutter:   spaceSettingsApps => /:spaceId([!#][^/]+)/settings/app
flutter:   spaceSettingsNotifications => /:spaceId([!#][^/]+)/settings/notifications
flutter:   tasks => /tasks
flutter:   task => /tasks/:taskListId([^/]+)/:taskId([^/]+)
flutter:   taskList => /tasks/:taskListId([^/]+)
flutter:   pins => /pins
flutter:   pin => /pins/:pinId
flutter:   calendarEvents => /events
flutter:   createEvent => /events/create
flutter:   editCalendarEvent => /events/:calendarId/edit
flutter:   calendarEvent => /events/:calendarId
flutter:   chat => /chat
flutter:   chatroom => /chat/:roomId([!#][^/]+)
flutter:   chatProfile => /chat/:roomId([!#][^/]+)/profile
flutter:   activities => /activities
flutter: 
flutter: INFO: 2024-03-29 12:32:41.114235: setting initial location /
[GoRouter] Full paths for routes:
  => /forward
  => /intro
  => /start
  => /introProfile
  => /login
  => /forgotPassword
  => /register
  => /bug-report
  => /error
  => /quick-jump
  => /actions/addPin
  => /actions/addTaskList
  => /actions/createSuperInvite
  => /spaces/create
  => /:spaceId([!#][^/]+)/linkChat
  => /:spaceId([!#][^/]+)/linkSubspace
  => /:spaceId([!#][^/]+)/linkRecommended
  => /actions/addUpdate
  => /:spaceId([!#][^/]+)/edit
  => /:spaceId([!#][^/]+)/invite
  => /:roomId([!#][^/]+)/invite
  => /chat/create
  => /
  => /search
  => /dashboard
  => /settings
  => /info/licenses
  => /settings/labs
  => /settings/notifications
  => /settings/super_invites
  => /info
  => /profile
  => /settings/sessions
  => /settings/language
  => /settings/emailAddresses
  => /settings/blockedUsers
  => /:spaceId([!#][^/]+)/spaces
  => /:spaceId([!#][^/]+)/members
  => /:spaceId([!#][^/]+)/pins
  => /:spaceId([!#][^/]+)/events
  => /:spaceId([!#][^/]+)/chats
  => /:spaceId([!#][^/]+)/tasks
  => /:spaceId([!#][^/]+)
  => /spaces/join
  => /spaces
  => /:spaceId([!#][^/]+)/settings
  => /:spaceId([!#][^/]+)/settings/app
  => /:spaceId([!#][^/]+)/settings/notifications
  => /tasks
  => /tasks/:taskListId([^/]+)/:taskId([^/]+)
  => /tasks/:taskListId([^/]+)
  => /pins
  => /pins/:pinId
  => /events
  => /events/create
  => /events/:calendarId/edit
  => /events/:calendarId
  => /chat
  => /chat/:roomId([!#][^/]+)
  => /chat/:roomId([!#][^/]+)/profile
  => /activities
known full paths for route names:
  forward => /forward
  intro => /intro
  start => /start
  introProfile => /introProfile
  authLogin => /login
  forgotPassword => /forgotPassword
  authRegister => /register
  bugReport => /bug-report
  fatalFail => /error
  quickJump => /quick-jump
  actionAddPin => /actions/addPin
  actionAddTaskList => /actions/addTaskList
  actionCreateSuperInvite => /actions/createSuperInvite
  createSpace => /spaces/create
  linkChat => /:spaceId([!#][^/]+)/linkChat
  linkSubspace => /:spaceId([!#][^/]+)/linkSubspace
  linkRecommended => /:spaceId([!#][^/]+)/linkRecommended
  actionAddUpdate => /actions/addUpdate
  editSpace => /:spaceId([!#][^/]+)/edit
  spaceInvite => /:spaceId([!#][^/]+)/invite
  chatInvite => /:roomId([!#][^/]+)/invite
  createChat => /chat/create
  main => /
  search => /search
  dashboard => /dashboard
  settings => /settings
  licenses => /info/licenses
  settingsLabs => /settings/labs
  settingNotifications => /settings/notifications
  settingsSuperInvites => /settings/super_invites
  info => /info
  myProfile => /profile
  settingSessions => /settings/sessions
  settingLanguage => /settings/language
  emailAddresses => /settings/emailAddresses
  blockedUsers => /settings/blockedUsers
  spaceRelatedSpaces => /:spaceId([!#][^/]+)/spaces
  spaceMembers => /:spaceId([!#][^/]+)/members
  spacePins => /:spaceId([!#][^/]+)/pins
  spaceEvents => /:spaceId([!#][^/]+)/events
  spaceChats => /:spaceId([!#][^/]+)/chats
  spaceTasks => /:spaceId([!#][^/]+)/tasks
  space => /:spaceId([!#][^/]+)
  joinSpace => /spaces/join
  spaces => /spaces
  spaceSettings => /:spaceId([!#][^/]+)/settings
  spaceSettingsApps => /:spaceId([!#][^/]+)/settings/app
  spaceSettingsNotifications => /:spaceId([!#][^/]+)/settings/notifications
  tasks => /tasks
  task => /tasks/:taskListId([^/]+)/:taskId([^/]+)
  taskList => /tasks/:taskListId([^/]+)
  pins => /pins
  pin => /pins/:pinId
  calendarEvents => /events
  createEvent => /events/create
  editCalendarEvent => /events/:calendarId/edit
  calendarEvent => /events/:calendarId
  chat => /chat
  chatroom => /chat/:roomId([!#][^/]+)
  chatProfile => /chat/:roomId([!#][^/]+)/profile
  activities => /activities

[GoRouter] setting initial location /
flutter: log settings: matrix_sdk::http_client=debug,acter::sync_response::full=trace,warn
flutter: logs will be found in /Users/kumarpalsinh/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3/DEV
flutter: INFO: 2024-03-29 12:32:42.564622: Prior log file: /Users/kumarpalsinh/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3/DEV/app_2024-03-28_16-19-33.122534.log
flutter: INFO: 2024-03-29 12:32:42.567892: Secure Store: available. Attempting to read.
flutter: INFO: 2024-03-29 12:32:42.568084: Secure Store: attempting to check if sessions exists
flutter: INFO: 2024-03-29 12:32:42.571861: Secure Store: decoding sessions
flutter: INFO: 2024-03-29 12:32:42.572019: Secure Store: decoding sessions: 1 found
flutter: INFO: 2024-03-29 12:32:42.572126: Secure Store[JCVFAUMNLR]: attempting to read session
[a3::sdk] Prior log file: /Users/kumarpalsinh/Library/Containers/global.acter.a3/Data/Library/Caches/global.acter.a3/DEV/app_2024-03-28_16-19-33.122534.log
[a3::sdk] Secure Store: available. Attempting to read.
[a3::sdk] Secure Store: attempting to check if sessions exists
[a3::sdk] Secure Store: decoding sessions
flutter: INFO: 2024-03-29 12:32:42.577159: Secure Store[JCVFAUMNLR]: token found
[a3::sdk] Secure Store: decoding sessions: 1 found
[a3::sdk] Secure Store[JCVFAUMNLR]: attempting to read session
[a3::sdk] Secure Store[JCVFAUMNLR]: token found
flutter: handle error - address: 105553172456256 ; len: 36
flutter: Fatal error: Operation not permitted (os error 1)
flutter: Stack: 
flutter: INFO: 2024-03-29 12:32:42.588632: getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
[GoRouter] getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
flutter: INFO: 2024-03-29 12:32:42.598970: redirecting to RouteMatchList#70e3b(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#37a44(route: GoRoute#5ffda(parentNavKey: [LabeledGlobalKey<NavigatorState>#4a938 root], name: "fatalFail", path: "/error"))])
flutter: Fatal error: Operation not permitted (os error 1)
flutter: Stack: 
flutter: INFO: 2024-03-29 12:32:42.599884: getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
flutter: INFO: 2024-03-29 12:32:42.600423: redirecting to RouteMatchList#70e3b(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#37a44(route: GoRoute#5ffda(parentNavKey: [LabeledGlobalKey<NavigatorState>#4a938 root], name: "fatalFail", path: "/error"))])
[GoRouter] redirecting to RouteMatchList#70e3b(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#37a44(route: GoRoute#5ffda(parentNavKey: [LabeledGlobalKey<NavigatorState>#4a938 root], name: "fatalFail", path: "/error"))])
[GoRouter] getting location for name: "fatalFail", queryParameters: {error: Operation not permitted (os error 1), trace: }
[GoRouter] redirecting to RouteMatchList#70e3b(uri: /error?error=Operation+not+permitted+%28os+error+1%29&trace, matches: [RouteMatch#37a44(route: GoRoute#5ffda(parentNavKey: [LabeledGlobalKey<NavigatorState>#4a938 root], name: "fatalFail", path: "/error"))])
flutter: INFO: 2024-03-29 12:32:42.610976: Using MaterialApp configuration
[GoRouter] Using MaterialApp configuration
```
